### ISSUE TITLE
Cannot open page 130455

### ISSUE THREAD

**Issue by tscottjendev** [jimmymcp/al-test-runner#139]
Next problem.  Getting this "Cannot open page 130455" when trying to run my tests.  Page definitely exists.
![image](https://github.com/jimmymcp/al-test-runner/assets/102963427/23b577d7-c7e6-49b4-98c2-2fc23316b878)

Terminal Output:

> PS Z:\Shared\Todd\Repos\Github\tscottjendev\Katas\RomanNumeral-Test> if ($null -eq (Get-Module ALTestRunner)) {Import-Module "c:\Users\Dev_TSCOTT\.vscode\extensions\jamespearson.al-test-runner-10.10.12\PowerShell\ALTestRunner.psm1" -DisableNameChecking}
> PS Z:\Shared\Todd\Repos\Github\tscottjendev\Katas\RomanNumeral-Test>  
> PS Z:\Shared\Todd\Repos\Github\tscottjendev\Katas\RomanNumeral-Test> cd "z:\Shared\Todd\Repos\Github\tscottjendev\Katas\RomanNumeral-Test"
> PS Z:\Shared\Todd\Repos\Github\tscottjendev\Katas\RomanNumeral-Test> Invoke-ALTestRunner -Tests Test -ExtensionId "eb641615-e41e-49ec-b474-be983946a7fd" -ExtensionName "RomanNumeral-Test" -FileName "z:\Shared\Todd\Repos\Github\tscottjendev\Katas\RomanNumeral-Test\src\ArabicRomanNumeralTest.Codeunit.al" -SelectionStart 10 -LaunchConfig '{"name":"Your own server","request":"launch","type":"al","environmentType":"OnPrem","server":"https://bc23ts","serverInstance":"BC","authentication":"UserPassword","breakOnError":"All","launchBrowser":true,"enableLongRunningSqlStatements":true,"enableSqlInformationDebugger":true,"tenant":"default","usePublicURLFromServer":true}' -GetPerformanceProfile
> Importing module bccontainerhelper
> BcContainerHelper version 6.0.7
> Setting bcartifactsCacheFolder = z:\bcartifacts.cache
> BC.HelperFunctions emits usage statistics telemetry to Microsoft
> Running on Windows, PowerShell 7.3.2
> Running tests on bc23ts, company CRONUS UK Ltd., tenant default, codeunit 50150, function OneToI, extension RomanNumeral-Test, test runner 130450, culture en-US
> Connecting to https://localhost:443/BC/cs?tenant=default&company=CRONUS%20UK%20Ltd.
> ERROR DIALOG: You do not have access to Dynamics 365 Business Central. Verify that you have been set up as a valid user in Dynamics 365 Business Central.
> at Run-Tests, C:\ProgramData\BcContainerHelper\Extensions\bc23ts\PsTestTool\PsTestFunctions.ps1: line 537
> at <ScriptBlock>, C:\ProgramData\BcContainerHelper\55b048ec-2d56-46ce-af43-372ad0109dfa.ps1: line 117
> at <ScriptBlock>, C:\ProgramData\BcContainerHelper\55b048ec-2d56-46ce-af43-372ad0109dfa.ps1: line 43
> at <ScriptBlock>, <No file>: line 1
> Cannot open page 130455. You might need to import the test toolkit to the container and/or remove the folder C:\ProgramData\BcContainerHelper\Extensions\bc23ts\PsTestTool and retry. You might also have URL or Company name wrong.
> 
> Container Free Physical Memory: 3.8Gb
> 
> Services in container bc23ts:
> - MicrosoftDynamicsNavServer$BC is Running
> - MSSQL$SQLEXPRESS is Running
> 
> 
> Relevant event log from container bc23ts:
> - 20240328 09:29:43 - MicrosoftDynamicsNavServer$BC
> 
>   Server instance: BC
>   Category: Reporting
>   ClientSessionId: 00000000-0000-0000-0000-000000000000
>   ClientActivityId: 5731592a-ff58-48c6-b223-d25192b5cfc5
>   ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
>   ServerActivityId: 00000000-0000-0000-0000-000000000000
>   EventTime: 03/28/2024 09:29:43
>   Message (SideServiceProcessException): RootException: SideServiceProcessException
>   Could not ensure side service is alive: C:\Program Files\Microsoft Dynamics NAV\230\Service\SideServices\Microsoft.BusinessCentral.Reporting.Service.exe
>   ExceptionStackTrace:
>      at Microsoft.Dynamics.Nav.Runtime.SideServiceProcessClient.EnsureAlive()
>      at Microsoft.Dynamics.Nav.Runtime.SideServiceWatchdog.<>c.<<CheckServices>b__9_0>d.MoveNext()
>   CallerStackTrace:
>      at Microsoft.Dynamics.Nav.Runtime.SideServiceWatchdog.<>c.<<CheckServices>b__9_0>d.MoveNext()
>      at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
> 
> - 20240328 09:29:43 - MicrosoftDynamicsNavServer$BC
> 
>   Server instance: BC
>   Category: Reporting
>   ClientSessionId: 00000000-0000-0000-0000-000000000000
>   ClientActivityId: 5731592a-ff58-48c6-b223-d25192b5cfc5
>   ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
>   ServerActivityId: 00000000-0000-0000-0000-000000000000
>   EventTime: 03/28/2024 09:29:43
>   Message (SideServiceProcessException): ParentException: SideServiceProcessException
>   Message not shown because the NavBaseException constructor was used without privacy classification
>   ExceptionStackTrace:
>      at Microsoft.Dynamics.Nav.Runtime.ReportingProcessStartup.InitializeReportingServiceConfiguration()
>      at Microsoft.Dynamics.Nav.Runtime.ReportingProcessStartup.OnAfterStarted()
>      at Microsoft.Dynamics.Nav.Runtime.SideServiceProcessClient.TryStartService()
>   InnerException:
>   RootException: NavNCLOperationCanceledException
> 
> - 20240328 09:29:28 - MicrosoftDynamicsNavServer$BC
> 
>   Server instance: BC
>   Category: Reporting
>   ClientSessionId: 00000000-0000-0000-0000-000000000000
>   ClientActivityId: 1a11283d-ada5-42a8-8adc-1116ca686530
>   ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
>   ServerActivityId: 00000000-0000-0000-0000-000000000000
>   EventTime: 03/28/2024 09:29:28
>   Message (SideServiceProcessException): RootException: SideServiceProcessException
>   Could not ensure side service is alive: C:\Program Files\Microsoft Dynamics NAV\230\Service\SideServices\Microsoft.BusinessCentral.Reporting.Service.exe
>   ExceptionStackTrace:
>      at Microsoft.Dynamics.Nav.Runtime.SideServiceProcessClient.EnsureAlive()
>      at Microsoft.Dynamics.Nav.Runtime.SideServiceWatchdog.<>c.<<CheckServices>b__9_0>d.MoveNext()
>   CallerStackTrace:
>      at Microsoft.Dynamics.Nav.Runtime.SideServiceWatchdog.<>c.<<CheckServices>b__9_0>d.MoveNext()
>      at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
> 
> - 20240328 09:29:28 - MicrosoftDynamicsNavServer$BC
> 
>   Server instance: BC
>   Category: Reporting
>   ClientSessionId: 00000000-0000-0000-0000-000000000000
>   ClientActivityId: 1a11283d-ada5-42a8-8adc-1116ca686530
>   ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
>   ServerActivityId: 00000000-0000-0000-0000-000000000000
>   EventTime: 03/28/2024 09:29:28
>   Message (SideServiceProcessException): ParentException: SideServiceProcessException
>   Message not shown because the NavBaseException constructor was used without privacy classification
>   ExceptionStackTrace:
>      at Microsoft.Dynamics.Nav.Runtime.ReportingProcessStartup.InitializeReportingServiceConfiguration()
>      at Microsoft.Dynamics.Nav.Runtime.ReportingProcessStartup.OnAfterStarted()
>      at Microsoft.Dynamics.Nav.Runtime.SideServiceProcessClient.TryStartService()
>   InnerException:
>   RootException: NavNCLOperationCanceledException
> 
> Run-TestsInBCContainer Telemetry Correlation Id: e1917685-f187-4bf7-bf50-08f851fd05a0
> Error occurred (Cannot open page 130455. You might need to import the test toolkit to the container and/or remove the folder C:\ProgramData\BcContainerHelper\Extensions\bc23ts\PsTestTool and retry. You might also have URL or Company name wrong.)
> Testing company set in config file exists in the container
> Running tests on bc23ts, company CRONUS UK Ltd., tenant default, codeunit 50150, function OneToI, extension RomanNumeral-Test, test runner 130450, culture en-US
> Connecting to https://localhost:443/BC/cs?tenant=default&company=CRONUS%20UK%20Ltd.
> ERROR DIALOG: You do not have access to Dynamics 365 Business Central. Verify that you have been set up as a valid user in Dynamics 365 Business Central.
> at Run-Tests, C:\ProgramData\BcContainerHelper\Extensions\bc23ts\PsTestTool\PsTestFunctions.ps1: line 537
> at <ScriptBlock>, C:\ProgramData\BcContainerHelper\71771b06-3fe2-4375-9e64-546c164afb80.ps1: line 117
> at <ScriptBlock>, C:\ProgramData\BcContainerHelper\71771b06-3fe2-4375-9e64-546c164afb80.ps1: line 43
> at <ScriptBlock>, <No file>: line 1
> Cannot open page 130455. You might need to import the test toolkit to the container and/or remove the folder C:\ProgramData\BcContainerHelper\Extensions\bc23ts\PsTestTool and retry. You might also have URL or Company name wrong.
> 
> Container Free Physical Memory: 3.8Gb
> 
> Services in container bc23ts:
> - MicrosoftDynamicsNavServer$BC is Running
> - MSSQL$SQLEXPRESS is Running
> 
> 
> Relevant event log from container bc23ts:
> - 20240328 09:31:29 - MicrosoftDynamicsNavServer$BC
> 
>   Server instance: BC
>   Category: Reporting
>   ClientSessionId: 00000000-0000-0000-0000-000000000000
>   ClientActivityId: 5ead71f8-482a-412e-ab62-0d567164ff9a
>   ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
>   ServerActivityId: 00000000-0000-0000-0000-000000000000
>   EventTime: 03/28/2024 09:31:29
>   Message (SideServiceProcessException): RootException: SideServiceProcessException
>   Could not ensure side service is alive: C:\Program Files\Microsoft Dynamics NAV\230\Service\SideServices\Microsoft.BusinessCentral.Reporting.Service.exe
>   ExceptionStackTrace:
>      at Microsoft.Dynamics.Nav.Runtime.SideServiceProcessClient.EnsureAlive()
>      at Microsoft.Dynamics.Nav.Runtime.SideServiceWatchdog.<>c.<<CheckServices>b__9_0>d.MoveNext()
>   CallerStackTrace:
>      at Microsoft.Dynamics.Nav.Runtime.SideServiceWatchdog.<>c.<<CheckServices>b__9_0>d.MoveNext()
>      at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
> 
> - 20240328 09:31:29 - MicrosoftDynamicsNavServer$BC
> 
>   Server instance: BC
>   Category: Reporting
>   ClientSessionId: 00000000-0000-0000-0000-000000000000
>   ClientActivityId: 5ead71f8-482a-412e-ab62-0d567164ff9a
>   ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
>   ServerActivityId: 00000000-0000-0000-0000-000000000000
>   EventTime: 03/28/2024 09:31:29
>   Message (SideServiceProcessException): ParentException: SideServiceProcessException
>   Message not shown because the NavBaseException constructor was used without privacy classification
>   ExceptionStackTrace:
>      at Microsoft.Dynamics.Nav.Runtime.ReportingProcessStartup.InitializeReportingServiceConfiguration()
>      at Microsoft.Dynamics.Nav.Runtime.ReportingProcessStartup.OnAfterStarted()
>      at Microsoft.Dynamics.Nav.Runtime.SideServiceProcessClient.TryStartService()
>   InnerException:
>   RootException: NavNCLOperationCanceledException
> 
> - 20240328 09:31:14 - MicrosoftDynamicsNavServer$BC
> 
>   Server instance: BC
>   Category: Reporting
>   ClientSessionId: 00000000-0000-0000-0000-000000000000
>   ClientActivityId: c4496b68-f163-4d5f-8878-fe67e6ca2612
>   ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
>   ServerActivityId: 00000000-0000-0000-0000-000000000000
>   EventTime: 03/28/2024 09:31:14
>   Message (SideServiceProcessException): RootException: SideServiceProcessException
>   Could not ensure side service is alive: C:\Program Files\Microsoft Dynamics NAV\230\Service\SideServices\Microsoft.BusinessCentral.Reporting.Service.exe
>   ExceptionStackTrace:
>      at Microsoft.Dynamics.Nav.Runtime.SideServiceProcessClient.EnsureAlive()
>      at Microsoft.Dynamics.Nav.Runtime.SideServiceWatchdog.<>c.<<CheckServices>b__9_0>d.MoveNext()
>   CallerStackTrace:
>      at Microsoft.Dynamics.Nav.Runtime.SideServiceWatchdog.<>c.<<CheckServices>b__9_0>d.MoveNext()
>      at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
> 
> - 20240328 09:31:14 - MicrosoftDynamicsNavServer$BC
> 
>   Server instance: BC
>   Category: Reporting
>   ClientSessionId: 00000000-0000-0000-0000-000000000000
>   ClientActivityId: c4496b68-f163-4d5f-8878-fe67e6ca2612
>   ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
>   ServerActivityId: 00000000-0000-0000-0000-000000000000
>   EventTime: 03/28/2024 09:31:14
>   Message (SideServiceProcessException): ParentException: SideServiceProcessException
>   Message not shown because the NavBaseException constructor was used without privacy classification
>   ExceptionStackTrace:
>      at Microsoft.Dynamics.Nav.Runtime.ReportingProcessStartup.InitializeReportingServiceConfiguration()
>      at Microsoft.Dynamics.Nav.Runtime.ReportingProcessStartup.OnAfterStarted()
>      at Microsoft.Dynamics.Nav.Runtime.SideServiceProcessClient.TryStartService()
>   InnerException:
>   RootException: NavNCLOperationCanceledException
> 
> Run-TestsInBCContainer Telemetry Correlation Id: e5875a97-090b-4372-b6db-69033400b92c
> Error occurred (Cannot open page 130455. You might need to import the test toolkit to the container and/or remove the folder C:\ProgramData\BcContainerHelper\Extensions\bc23ts\PsTestTool and retry. You might also have URL or Company name wrong.)
> Testing company set in config file exists in the container
> PS Z:\Shared\Todd\Repos\Github\tscottjendev\Katas\RomanNumeral-Test>

**Comment by jimmymcp** [comment]
Please check that the credentials stored in the .altestrunner/config.json file are valid. You can clear the credentials with AL Test Runner: Clear Credentials command in VS Code and you should be prompted to enter them again when you run a test.
